spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource



## camunda登录信息配置
camunda.bpm:
  admin-user:
    id: admin  ##用户名
    password: 123456  ##密码
    firstName: yu
  filter:
    create: All tasks


